FROM FROM ubuntu:20.04

USER root

ENV DEBIAN_FRONTEND=noninteractive

##############
# apt update #
##############
RUN apt-get update
RUN apt-get install -y wget git build-essential libgl1-mesa-dev libfreetype6-dev libglu1-mesa-dev libzmq3-dev libsqlite3-dev libicu-dev python3-dev libgl2ps-dev libfreeimage-dev libtbb-dev ninja-build bison autotools-dev automake libpcre3 libpcre3-dev tcl8.6 tcl8.6-dev tk8.6 tk8.6-dev libxmu-dev libxi-dev libopenblas-dev libboost-all-dev swig libxml2-dev cmake rapidjson-dev
RUN dpkg-reconfigure --frontend noninteractive tzdata


############################################################
# OCCT 7.5.3                                               #
# Download the official source package from git repository #
############################################################
WORKDIR /opt/build
RUN wget 'https://git.dev.opencascade.org/gitweb/?p=occt.git;a=snapshot;h=fecb042498514186bd37fa621cdcf09eb61899a3;sf=tgz' -O occt-fecb042.tar.gz
RUN tar -zxvf occt-fecb042.tar.gz >> extracted_occt753_files.txt
RUN mkdir occt-fecb042/build
WORKDIR /opt/build/occt-fecb042/build

RUN cmake -G Ninja \
 -DINSTALL_DIR=/opt/build/occt753 \
 -DBUILD_RELEASE_DISABLE_EXCEPTIONS=OFF \
 ..

RUN ninja install

RUN echo "/opt/build/occt753/lib" >> /etc/ld.so.conf.d/occt.conf
RUN ldconfig

#############
# pythonocc #
#############
WORKDIR /opt/build
RUN git clone https://github.com/tpaviot/pythonocc-core
WORKDIR /opt/build/pythonocc-core
#RUN git checkout 7.5.1
WORKDIR /opt/build/pythonocc-core/build

RUN cmake \
 -DOCE_INCLUDE_PATH=/opt/build/occt753/include/opencascade \
 -DOCE_LIB_PATH=/opt/build/occt753/lib \
 -DPYTHONOCC_BUILD_TYPE=Release \
 ..

RUN make -j3 && make install 

############
# svgwrite #
############
RUN pip install svgwrite

#######################
# Run pythonocc tests #
#######################
WORKDIR /opt/build/pythonocc-core/test
RUN python core_wrapper_features_unittest.py

##############################
# Install pythonocc examples #
##############################
#WORKDIR /opt/build/
#RUN git clone https://github.com/tpaviot/pythonocc-demos
#WORKDIR /opt/build/pythonocc-demos
#RUN cp -r /opt/build/pythonocc-demos/assets /home/jovyan/work
#RUN cp -r /opt/build/pythonocc-demos/jupyter_notebooks /home/jovyan/work

########
# gmsh #
########
ENV CASROOT=/opt/build/occt753
WORKDIR /opt/build
RUN git clone https://gitlab.onelab.info/gmsh/gmsh
WORKDIR /opt/build/gmsh
RUN git checkout gmsh_4_9_0
WORKDIR /opt/build/gmsh/build

RUN cmake \
 -DCMAKE_BUILD_TYPE=RelWithDebInfo \
 -DENABLE_OCC=ON \
 -DENABLE_OCC_CAF=ON \
 -DCMAKE_INSTALL_PREFIX=/usr/local \
 ..

RUN make && make install
